import "../globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LocalStorageProvider } from "./components/LocalStorageAsContext";
import { DiccionarioProvider } from "./components/DiccionarioContext";
import { getDictionary } from "./diccionarios";
import { ApiProvider } from "./components/APIDogs";
import  Header from "./components/Header";
import { Footer } from "./components/Footer";

/**
 * Root layout de la aplicación.
 *
 * Al vivir dentro de `[lang]`, este es el layout raíz de TODAS las rutas
 * (el proxy garantiza que siempre haya un locale en la URL). Se encarga de:
 *  - cargar las fuentes Geist como variables CSS,
 *  - montar los estilos globales (Tailwind),
 *  - envolver el árbol en `LocalStorageProvider`, para que cualquier client
 *    component pueda leer/escribir las series persistidas en localStorage,
 *  - cargar el diccionario del idioma y publicarlo en `DiccionarioProvider`,
 *    para que los client components lean los textos sin recibirlos por props.
 */

/** Fuente sans-serif expuesta como variable CSS `--font-geist-sans`. */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/** Fuente monoespaciada expuesta como variable CSS `--font-geist-mono`. */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/** Metadatos por defecto (<title> y <meta description>) para todas las páginas. */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @param children Página (y layouts anidados) que se renderiza dentro del body.
 * @param params   Promesa con los segmentos dinámicos de la ruta; aquí `{ lang }`.
 */
export default async function RootLayout({ children, params }: LayoutProps<"/[lang]">) {
  // En Next.js 16 `params` es una promesa: hay que await-earla antes de usarla.
  const { lang } = await params;
  // El diccionario se resuelve aquí (servidor) y baja una sola vez al cliente
  // dentro del payload de RSC. `getDictionary` responde 404 si el locale no existe.
  const dict = await getDictionary();
  return (
    <html
      // NOTA: `lang` se extrae pero no se aplica al elemento <html lang={lang}>.
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* El provider debe envolver todo: las páginas de series leen su contexto. */}
        {/* NOTA: las comillas invertidas sueltas del final se renderizan como texto. */}
        <DiccionarioProvider dict={dict} lang={lang}>
          <ApiProvider>
            <LocalStorageProvider>
              <Header />
              {children}
              <Footer />
            </LocalStorageProvider>
          </ApiProvider>
        </DiccionarioProvider>
  
      </body>
    </html>
  );
}
